pre-commit:
  parallel: true
  commands:
    type-check:
      glob: "*.{ts,tsx}"
      run: npm run typecheck
    eslint:
      glob: "*.{ts,tsx}"
      run: npm run lint:fix {staged_files}
    spelling:
      glob: "*.{ts,tsx,md}"
      run: npm run cspell {staged_files}

commit-msg:
  commands:
    parallel: true
    lint-commit-msg:
      run: npx commitlint --edit
    spell-check:
      run: npm run cspell --no-summary {1}
